# Generated by Django 5.0.14 on 2026-06-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
