# Generated by Django 5.0.14 on 2026-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
