# Generated by Django 5.0.14 on 2026-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_note_parent_alter_note_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='calendar_event_id',
            field=models.CharField(blank=True, help_text='Remote calendar unique tracking resource token reference.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Timezone-aware deadline target timestamp.', null=True),
        ),
    ]
