# Generated by Django 5.0.14 on 2026-06-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_note_parent_alter_note_content_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='calendar_event_id',
            field=models.CharField(blank=True, help_text='Remote calendar unique tracking resource token reference.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Timezone-aware deadline target timestamp.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='related_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='notes.note'),
        ),
    ]
